In [2]:
import numpy as np
#1 to 

__[sort search count](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.sort.html)__

# 創造

In [3]:
#np.arange(0,6,1)   #創造
#np.zeros((2,3))
print("3.",np.random.rand(4,5))
print("4.",np.ones((2, 2), dtype=bool))
print(np.full(10,True))

3. [[0.15889366 0.49303314 0.20816062 0.17599975 0.35411996]
 [0.57743183 0.94563562 0.54431419 0.18313164 0.61410067]
 [0.47061656 0.83163114 0.80043661 0.1984024  0.99340405]
 [0.27674128 0.29557526 0.19050302 0.24502094 0.71455468]]
4. [[ True  True]
 [ True  True]]
[ True  True  True  True  True  True  True  True  True  True]


In [33]:
x=np.arange(-50,55,5)
z=np.arange(0,10,1)
#z=z[::-1]
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
xs=x/50
zs=(z/9)
zs=zs.reshape(zs.shape[0],1)
ys=(2*zs-zs**2)*(1-xs**2)*(1+xs**2+xs**4)
y=ys*7.5
y

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.73754657, 1.16144   , 1.38888583, 1.50063407,
        1.54947917, 1.56762667, 1.57292657, 1.57397333, 1.5740725 ,
        1.57407407, 1.5740725 , 1.57397333, 1.57292657, 1.56762667,
        1.54947917, 1.50063407, 1.38888583, 1.16144   , 0.73754657,
        0.        ],
       [0.        , 1.38832296, 2.18624   , 2.61437333, 2.82472296,
        2.91666667, 2.95082667, 2.96080296, 2.96277333, 2.96296   ,
        2.96296296, 2.96296   , 2.96277333, 2.96080296, 2.95082667,
        2.91666667, 2.82472296, 2.61437333, 2.18624   , 1.38832296,
        0.        ],
       [0.        , 1.95232917, 3.0744    , 3.6764625 , 3.97226667,
        4.1015625 , 4.1496    , 4.16362917, 4.1664   

In [38]:
import pandas as pd
df=pd.DataFrame(y,columns=x,index=z)
df
df.to_csv("ship.csv",encoding='utf-8')

# 取值

In [4]:
a=np.array([[1,2,3],[4,5,6]])
#a[0]    #取值
print("#1",a>3)
print("#2",a[a>2])
print("#3",a[:,1])
print(a[[True,False]])
np.multiply.reduce(a)

#1 [[False False False]
 [ True  True  True]]
#2 [3 4 5 6]
#3 [2 5]
[[1 2 3]]


array([ 4, 10, 18])

NameError: name 'a' is not defined

In [11]:
np.array([True,False]).shape

(2,)

In [12]:
a=np.array([1,2,3])
b=np.array([1,2,3])
#np.dot(a,b)    #運算a & b
#a*b
a.reshape(a.shape[0],1)

array([[1],
       [2],
       [3]])

In [5]:
a=np.array([1,3,2,4,5,6])
print(a[0:2])
print(a[np.array([1,4])])
#a.reshape((3,2))       #形狀 順序
a.shape
a=np.array([[1,2,3],[3,2,1]])
print("#1",a.reshape(3,2))
print("#2",np.transpose(a))#行列互換
#a.sort(1)
#a.repeat(3,1)
np.argsort(a) #回傳Index


[1 3]
[3 5]
#1 [[1 2]
 [3 3]
 [2 1]]
#2 [[1 3]
 [2 2]
 [3 1]]


array([[0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [10]:
a=np.array([[1,2,3],[2,3,4]])
np.sum(a,1)     #運算 a & a
#np.sum(a,0)
#np.sin(a)


array([6, 9])

In [8]:
a=np.array([[1,2,3],[1,2,3]])
b=np.array([[1],[2]])
b.shape


(2, 1)

# ax+b  in:(a,b)   out:x

In [4]:
a=np.array([[1,-1,-1,0,0,0],
           [0,0,1,-1,-1,0],
           [0,1,0,1,0,-1],
           [0,-80,0,0,0,-50],
           [0,-80,800,40,0,0],
           [0,0,0,40,-200,50]])
b=np.array([0,-0.75,0,-50,0,0])
np.linalg.solve(a, b)

array([ 0.196,  0.2  , -0.004,  0.48 ,  0.266,  0.68 ])

In [14]:
a=np.array([1,0],dtype=bool)
b=np.array([1,1],dtype=bool)
a+b

array([ True,  True])

In [4]:
import dill
